name: macOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          architecture: x64
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop
      
      - name: Build macOS
        run: flutter build macos --release

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          create-dmg \
            --volname "Todo App" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "Todo_App.dmg" \
            "todo_app.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/Todo_App.dmg
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/macos/Build/Products/Release/Todo_App.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
